app/routes/login.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user, logout_user, current_user
from flask_dance.contrib.google import google
from app import bcrypt, db
from app.models import Usuario
from app.forms import LoginForm, RegisterForm
import os

login_bp = Blueprint('login', __name__)


@login_bp.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("main.home"))
    
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = Usuario.query.filter_by(name=form.name.data).first()

        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for("main.home"))
        else:
            flash("Invalid email and/or password.", "danger")
            print("----Error en el logueo------")
            return render_template("login.html", form=form)
    return render_template("login.html", form=form)

@login_bp.route('/logout')
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("main.home"))

@login_bp.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("main.home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Usuario(name=form.name.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in.", "success")
        return redirect(url_for("main.login"))
    return render_template("admin/register.html", form=form)


@login_bp.route('/google-login')
def google_login():
    if not google.authorized:
        return redirect(url_for('google.login'))

    resp = google.get('/oauth2/v2/userinfo')
    assert resp.ok, resp.text
    user_info = resp.json()

    # Busca un usuario existente con el email o crea uno nuevo
    email = user_info['email']
    user = Usuario.query.filter_by(email=email).first()

    if user is None:
        user = Usuario(username=user_info['name'], email=email)
        db.session.add(user)
        db.session.commit()

    login_user(user)
    return redirect(url_for('profile'))

app/routes/main.py
from flask import Blueprint, flash, redirect, render_template, request, url_for, jsonify
from flask_login import login_required, current_user
from datetime import datetime, timezone
from app import db
from app.models import Carrito, Producto, CarritoProducto, Transaccion
from app.forms import TarjetaForm
import mercadopago
import os


main_bp = Blueprint('main', __name__, template_folder='templates')

# Configura tu ACCESS_TOKEN
mp = mercadopago.SDK(os.getenv('MERCADO_PAGO_TOKEN'))


@main_bp.route('/')
def home():
    productos = Producto.query.all()
    return render_template('home.html', productos=productos)


@main_bp.route('/carrito')
@login_required
def carrito():
    carrito = Carrito.query.filter_by(usuario_id=current_user.id, comprado=False).first()

    if not carrito:
        return render_template('carrito.html', items=[])
    
    # Recuperar todos los productos en el carrito
    productos = (
        db.session.query(Producto, CarritoProducto)
        .join(CarritoProducto, Producto.id == CarritoProducto.producto_id)
        .filter(CarritoProducto.carrito_id == carrito.id)
        .all()
    )

    # Crear una lista de diccionarios para los datos del carrito
    items = []
    for producto, carrito_producto in productos:
        items.append({
            'id': producto.id,
            'nombre': producto.nombre,
            'precio': producto.precio,
            'cantidad': carrito_producto.cantidad,
            'total': producto.precio * carrito_producto.cantidad
        })

    return render_template('carrito.html', items=items, carrito_id=carrito.id)

@main_bp.route('/tusCompras')
@login_required
def tusCompras():
    carritos = Carrito.query.filter_by(usuario_id=current_user.id, comprado=True)

    if not carritos:
        return render_template('carrito.html', items=[])
    
    
    carritosProductos = []
    # Recuperar todos los productos en el carrito
    for carrito in carritos:
        productos = (
            db.session.query(Producto, CarritoProducto)
            .join(CarritoProducto, Producto.id == CarritoProducto.producto_id)
            .filter(CarritoProducto.carrito_id == carrito.id)
            .all()
        )
        # Crear una lista de diccionarios para los datos del carrito
        items = []
        for producto, carrito_producto in productos:
            items.append({
                'id': producto.id,
                'nombre': producto.nombre,
                'precio': producto.precio,
                'cantidad': carrito_producto.cantidad,
                'total': producto.precio * carrito_producto.cantidad
            })
        carritosProductos.append(items)

    return render_template('tusCompras.html', carritosProductos=carritosProductos)

@main_bp.route('/modificarCarrito/<int:product_id>/<action>', methods=['POST'])
@login_required
def modificarCarrito(product_id, action):
    carrito = Carrito.query.filter_by(usuario_id=current_user.id, comprado=False).first()

    if carrito:
        carrito_producto = CarritoProducto.query.filter_by(carrito_id=carrito.id, producto_id=product_id).first()

        if carrito_producto:
            if action == 'increase':
                carrito_producto.cantidad += 1
            elif action == 'decrease':
                if carrito_producto.cantidad > 1:
                    carrito_producto.cantidad -= 1
                else:
                    db.session.delete(carrito_producto)  # Eliminar el producto si la cantidad es 0
            elif action == 'remove':
                db.session.delete(carrito_producto)
    
            db.session.commit()
            flash('Carrito actualizado.', 'success')
        else:
            flash('Producto no encontrado en el carrito.', 'danger')
    else:
        flash('No hay carrito activo.', 'danger')

    return redirect(url_for('main.carrito'))

@main_bp.route('/agregarCarrito/<int:product_id>', methods=['POST'])
@login_required
def agregarCarrito(product_id):
    producto = Producto.query.get_or_404(product_id)
    carrito = Carrito.query.filter_by(usuario_id=current_user.id, comprado=False).first()

    if not carrito:
        # Crear un nuevo carrito para el usuario si no tiene uno
        carrito = Carrito(usuario_id=current_user.id, fecha=datetime.now(timezone.utc), comprado=False)
        db.session.add(carrito)
        db.session.commit()

    # Verificar si el producto ya está en el carrito
    carrito_producto = CarritoProducto.query.filter_by(carrito_id=carrito.id, producto_id=producto.id).first()

    if carrito_producto:
        # Si el producto ya está en el carrito, incrementa la cantidad
        carrito_producto.cantidad += 1
    else:
        # Si el producto no está en el carrito, lo añadimos con cantidad 1
        carrito_producto = CarritoProducto(carrito_id=carrito.id, producto_id=producto.id, cantidad=1)
        db.session.add(carrito_producto)

    db.session.commit()

    return jsonify({'status': 'success', 'message': f'{producto.nombre} ha sido añadido al carrito.'})


@main_bp.route('/comprar/<int:carrito_id>', methods=['GET'])
@login_required
def compra(carrito_id):
    # Obtener el carrito por su ID
    carrito = Carrito.query.get_or_404(carrito_id)

    # Verificar si el carrito pertenece al usuario actual y si no está ya comprado
    if carrito.usuario_id != current_user.id or carrito.comprado:
        flash('Acción no permitida o el carrito ya ha sido comprado.', 'danger')
        return redirect(url_for('main.carrito'))
    
    # Verificar si el usuario tiene los datos de la tarjeta completos
    if not current_user.numero_tarjeta or not current_user.vencimiento_tarjeta or not current_user.numero_seguridad_tarjeta:
        flash('Por favor, complete los datos de su tarjeta para realizar la compra.', 'warning')
        return redirect(url_for('main.completar_datos_tarjeta'))

    # Verificar si la tarjeta está vencida
    if current_user.vencimiento_tarjeta < datetime.now():
        flash('La tarjeta está vencida. Actualice los datos de pago.', 'danger')
        return redirect(url_for('main.carrito'))
    
    # Calcular el total de la compra
    carrito_productos = CarritoProducto.query.filter_by(carrito_id=carrito_id).all()
    total_compra = 0
    for item in carrito_productos:
        # Obtener el producto correspondiente
        producto = Producto.query.get(item.producto_id)

        # Verificar si hay suficiente stock
        if producto.stock >= item.cantidad:
            # Restar la cantidad del stock del producto
            producto.stock -= item.cantidad
            # Calcular el subtotal del producto
            subtotal = producto.precio * item.cantidad
            total_compra += subtotal
        else:
            flash(f"No hay suficiente stock para {producto.nombre}.", 'danger')
            return redirect(url_for('main.carrito'))

    # Verificar si el usuario tiene saldo suficiente en la tarjeta
    if current_user.plata < total_compra:
        flash('No tiene suficiente saldo en la tarjeta.', 'danger')
        return redirect(url_for('main.carrito'))

    # Restar el total de la compra del saldo de la tarjeta
    current_user.plata -= total_compra

    # Marcar el carrito como comprado
    carrito.comprado = True

    # Confirmar los cambios en la base de datos
    db.session.commit()

    # Redirigir a la página de comprobante de transacción
    return redirect(url_for('main.comprobante_transaccion', carrito_id=carrito_id, costo=total_compra))

@main_bp.route('/comprobante/<int:carrito_id>/<int:costo>', methods=['GET'])
@login_required
def comprobante_transaccion(carrito_id, costo):
    return render_template('comprobante_transaccion.html',costo=costo)

@main_bp.route('/completar_tarjeta', methods=['GET', 'POST'])
@login_required
def completar_datos_tarjeta():
    form = TarjetaForm()

    if form.validate_on_submit():
        # Guardar los datos de la tarjeta en el usuario actual
        current_user.numero_tarjeta = form.numero_tarjeta.data
        current_user.vencimiento_tarjeta = form.vencimiento_tarjeta.data
        current_user.numero_seguridad_tarjeta = form.numero_seguridad_tarjeta.data

        # Confirmar los cambios en la base de datos
        db.session.commit()

        flash('Datos de la tarjeta guardados correctamente.', 'success')
        return redirect(url_for('main.carrito'))

    return render_template('completar_datos_tarjeta.html', form=form)

@main_bp.route('/contacto')
def contacto():
    #Mucho codigo ...
    return render_template("contacto.html")


@main_bp.route('/checkout/<int:carrito_id>', methods=['POST'])
def checkout(carrito_id):
    carrito = Carrito.query.get_or_404(carrito_id)
    if carrito.comprado:
        return "Carrito ya comprado", 400

    if not carrito or not carrito.productos:
        return "No hay productos en el carrito.", 400



    items = []
    total_amount = 0
    carrito_producto = CarritoProducto.query.filter_by(carrito_id=carrito_id).all()
    for cart_product in carrito_producto:
        producto = Producto.query.get(cart_product.producto_id)
        items.append({
            "title": producto.nombre,
            "quantity": cart_product.cantidad,
            "unit_price": producto.precio,
            "currency_id": "ARS"
        })
        total_amount += producto.precio

    preference_data = {
        "items": items,
        "back_urls": {
            "success": url_for('main.success', _external=True),
            "failure": url_for('main.failure', _external=True),
            "pending": url_for('main.pending', _external=True)
        },
        "auto_return": "approved",
        "notification_url": url_for('main.notifications', _external=True)
    }

    preference_response = mp.preference().create(preference_data)
    preference_id = preference_response['response']['id']
    #init_point = preference_response['response']['init_point']

    # Guarda la transacción pendiente en la base de datos

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='favicon.ico')}}">
    <title>App de Cobro</title>
    <!-- styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    {% block css %}{% endblock %}
    <style>
         /* General Styles */
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f8f8f8;
    }

    nav {
        background-color: #343a40;
        padding: 10px 20px;
        text-align: center;
    }

    nav a {
        color: white;
        text-decoration: none;
        margin: 0 15px;
        font-weight: bold;
        transition: color 0.3s ease;
    }

    nav a:hover {
        color: #ffc107;
    }


    /* Container Styles */
    .container {
        padding: 20px;
        margin-top: 20px;
    }

    /* Footer Styles */
    footer {
        background-color: #343a40;
        color: white;
        text-align: center;
        padding: 10px 0;
        width: 100%;
    }
    </style>
</head>
<body>
    <nav class="d-flex justify-content-evenly">
        <h2 class="text-info">
            {% if current_user.is_authenticated %}
            <i class="fa-regular fa-user me-2"></i>
            {% endif %}
            {{current_user.name}}
        </h2>
        <div>
            <a href="{{ url_for('main.home') }}">Inicio</a>

            {% if current_user.is_authenticated %}
            <a href="{{ url_for('main.carrito') }}">Carrito</a>
            <a href="{{ url_for('main.tusCompras') }}">Tus Compras</a>
            <a href="{{ url_for('admin.crearProducto') }}">Añadir Productos</a>
            {% endif %}

            <a href="{{ url_for('main.contacto') }}">Contacto</a>
            
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('login.logout') }}" class="btn btn-danger">Cerrar Sesion</a>
            {% else %}
            <a href="{{ url_for('login.login') }}" class="btn btn-success" >Login</a>
            {% endif %}
        </div>
        <h2 class="text-info">
            {% if current_user.is_authenticated %}
            ${{current_user.plata|price_format}}
            {% endif %}
        </h2>
    </nav>
    

    <div class="d-flex justify-content-center">
        <div class="containter mt-4">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-danger text-center" role="alert">
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
            
            {%block content%}{%endblock%}
        </div>
    </div>
    {%block js%}{%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

app/templates/carrito.html
{% extends "base.html" %}

{% block content %}
<h2 class="mt-3">Tu Carrito</h2>

{% if items %}
<table class="table table-striped border shadow">
    <thead>
        <tr>
        <th scope="col">Producto</th>
        <th scope="col">Precio</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Total</th>
        <th scope="col">Accion</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.nombre }}</td>
            <td>${{ item.precio | price_format}}</td>
            <td>{{ item.cantidad }}</td>
            <td>${{ item.total | price_format }}</td>
            <td>
                <form action="{{ url_for('main.modificarCarrito', product_id=item.id, action='decrease') }}" method="POST" style="display:inline;">
                    <button type="submit" class="btn btn-sm">
                        <i class="fa-solid fa-minus"></i>
                    </button>
                </form>
                <form action="{{ url_for('main.modificarCarrito', product_id=item.id, action='increase') }}" method="POST" style="display:inline;">
                    <button type="submit" class="btn btn-sm">
                        <i class="fa-solid fa-plus"></i>
                    </button>
                </form>
                <form action="{{ url_for('main.modificarCarrito', product_id=item.id, action='remove') }}" method="POST" style="display:inline;">
                    <button type="submit" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash"></i>
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    <!-- Total del carrito -->
    <div class="mt-3">
    <h4 class="text-center">${{ items | map(attribute='total') | sum | price_format }} ARS</h4>

    <a href="{{url_for('main.compra', carrito_id=carrito_id) }}" class="btn btn-success w-100 mt-3">Comprar</a>
    <form id="form-checkout" method="POST" action="{{url_for('main.checkout', carrito_id=carrito_id) }}">
        <button type="submit" id="checkout-btn" class="btn btn-success w-100 mt-3">Comprar con MP</button>
    </form>
</div>
{% else %}
    <p>Your cart is empty.</p>
{% endif %}
 
{% endblock %}

{% block js %}
<script>
    const mp = new MercadoPago('TEST-5f05dac5-9fe3-42b2-bf0c-a1bb665a0df5', {
      locale: 'es-AR' // Configuración regional
    });
  
    // Crear el botón de pago dinámicamente
    mp.checkout({
      preference: {
        id: '{{ preference_id }}'  // La preferencia creada en Flask
      }
    });
  </script>
{% endblock %}

{% block css %}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f8f8f8;
    }

    header {
        background-color: #333;
        color: white;
        padding: 10px 20px;
        text-align: center;
    }

    .container {
        padding: 20px;
        margin: 0 auto;
        max-width: 800px;
    }

    h2 {
        text-align: center;
        margin-bottom: 20px;
    }

    .cart-table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    .cart-table th,
    .cart-table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }

    .cart-table th {
        background-color: #f2f2f2;
    }

    .cart-total {
        text-align: right;
    }

    .checkout-btn {
        background-color: #28a745;
        color: white;
        border: none;
        padding: 10px 20px;
        text-decoration: none;
        font-size: 1em;
        cursor: pointer;
        display: inline-block;
    }

    .checkout-btn:hover {
        background-color: #218838;
    }

    .remove-btn {
        background-color: #dc3545;
        color: white;
        border: none;
        padding: 5px 10px;
        cursor: pointer;
    }

    .remove-btn:hover {
        background-color: #c82333;
    }
</style>
{% endblock %}

app/templates/completar_datos_tarjeta.html
{% extends "base.html" %}

{% block content %}
<h1>Completar Datos de Tarjeta</h1>
    
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="mb-3">
    {{ form.numero_tarjeta.label(class="form-label") }}
    {{ form.numero_tarjeta(class="form-control") }}
    </div>
    <div class="mb-3">
    {{ form.vencimiento_tarjeta.label(class="form-label") }}
    {{ form.vencimiento_tarjeta(class="form-control") }}
    </div>
    <div class="mb-3">
    {{ form.numero_seguridad_tarjeta.label(class="form-label") }}
    {{ form.numero_seguridad_tarjeta(class="form-control") }}
    </div>
    <div class="mb-3">
    {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% endblock %}

{% block css %}
<style>
</style>
{% endblock %}

app/templates/comprobante_transaccion.html
{% extends "base.html" %}

{% block content %}
<h1>Compra realizada con exito!!!</h1>
<div>
    <h2>Por el usuario {{current_user.name}} con numero de tajeta terminado en ..{{ (current_user.numero_tarjeta|string)[-3:]}}</h2>
    <h2>Se han restado ${{costo|price_format}} de su cuenta</h2>
</div>
{% endblock %}

{% block css %}
<style>
</style>
{% endblock %}

app/templates/contacto.html
{% extends "base.html" %}

{% block content %}
<body>
    <header>
        <h1>Tienda en P&M Línea</h1>
    </header>

    <div class="container">
        <h2>Ponte en Contacto con Nosotros</h2>
        <p>Si tienes alguna pregunta o comentario, por favor completa el siguiente formulario.</p>

        <form action="" method="POST">
            <div class="form-group">
                <label for="name">Nombre:</label>
                <input type="text" id="name" name="name" required>
            </div>

            <div class="form-group">
                <label for="email">Correo Electrónico:</label>
                <input type="email" id="email" name="email" required>
            </div>

            <div class="form-group">
                <label for="message">Mensaje:</label>
                <textarea id="message" name="message" rows="5" required></textarea>
            </div>

            <button type="submit">Enviar Mensaje</button>
        </form>
    </div>

</body>
{% endblock %}

{% block css %}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f8f8f8;
    }

    header {
        background-color: #333;
        color: white;
        padding: 10px 20px;
        text-align: center;
    }

    .container {
        padding: 20px;
        margin: 0 auto;
        max-width: 600px;
    }

    h2 {
        text-align: center;
        margin-bottom: 20px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-group label {
        display: block;
        margin-bottom: 5px;
    }

    .form-group input[type="text"],
    .form-group input[type="email"],
    .form-group textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    button {
        background-color: #28a745;
        color: white;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 1em;
        border-radius: 4px;
        width: 100%;
    }

    button:hover {
        background-color: #218838;
    }
</style>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<body>
    <header>
        <h1>Tienda P&M en Línea</h1>
    </header>

    <div class="container">
        <div class="row">
            {% for producto in productos %}
              <div class="col-md-4">
                <div class="card mb-4 shadow carta-producto">
                  <!-- Mostrar la imagen del producto -->
                    <img src="{{ url_for('static', filename='uploads/' ~ producto.imagen) }}" class="card-img-top" alt="{{ producto.nombre }}">
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-2">
                            <h5 class="card-title text-start">{{ producto.nombre }}</h5>
                            <h4 class="card-text text-end">${{ producto.precio | price_format }} <i class="fs-6 text">ARS</i></h4>
                        </div>
                        <div class="d-flex justify-content-between align-items-end">
                            <p class="card-text mb-0"><strong>Stock:</strong> {{ producto.stock }}</p>
                            <form class="agregarCarritoForm d-flex align-items-end" data-route="{{ url_for('main.agregarCarrito', product_id=producto.id) }}">
                                <div class="spinner-border text-primary me-2 d-none" role="status">
                                    <span class="visually-hidden">Loading...</span>
                                </div>
                                <button type="submit" class="btn btn-primary btn-sm">
                                    <i class="fa-solid fa-cart-shopping"></i> Agregar al Carrito
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
              </div>
            {% else %}
              <p>No products found.</p>
            {% endfor %}
        </div>

        <div class="product">
            <img src="{{ url_for('static', filename='img/producto1.jpg') }}" alt="Producto 1">
            <h3>Iphone 12</h3>
            <p class="price">$849.99</p>
            <button>Agregar al Carrito</button>
        </div>

        <div class="product">
            <img src="{{ url_for('static', filename='img/producto2.jpg') }}" alt="Producto 2">
            <h3>Air Jordan</h3>
            <p class="price">$99.99</p>
            <button>Agregar al Carrito</button>
        </div>

        <div class="product">
            <img src="{{ url_for('static', filename='img/producto3.jpg') }}" alt="Producto 3">
            <h3>AirPods</h3>
            <p class="price">$129.99</p>
            <button>Agregar al Carrito</button>
        </div>
    </div>


</body>
{% endblock %}

{% block js %}
<script>
    const forms = document.querySelectorAll('.agregarCarritoForm')
    forms.forEach(form => {
        form.addEventListener('submit', function(event) {
          event.preventDefault(); // Evita el envío tradicional del formulario

          const spiner = form.querySelector(".spinner-border")
          spiner.classList.remove("d-none");
  
          fetch(this.getAttribute('data-route'), {method: 'POST'})
          .then(response => response.json())
          .then(data => {
            spiner.classList.add("d-none");
            if (data.status === 'success') {
              alert(data.message);
              // Aquí puedes actualizar la interfaz de usuario si es necesario
            } else {
              alert('Error al añadir el producto al carrito.');
            }
          })
          .catch(error => {
            console.error('Error:', error);
          });
        });
      });
</script>
{% endblock %}

{% block css %}
<style>
    .carta-producto{
        transition: transform 0.3s ease;
    }
    .carta-producto:hover{
        transform: scale(1.02);
    }

    /* General Styles */
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f8f8f8;
    }

    header {
        background-color: #333;
        color: white;
        padding: 10px 20px;
        text-align: center;
    }

    .container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        padding: 20px;
    }

    /* Product Styles */
    .product {
        background-color: white;
        border: 1px solid #ddd;
        margin: 10px;
        padding: 15px;
        width: 300px;
        text-align: center;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s ease;
    }

    .product img {
        width: 100%;
        height: auto;
    }

    .product h3 {
        margin: 10px 0;
        font-size: 1.2em;
        color: #333;
    }

    .product p {
        color: #666;
    }

    .product .price {
        font-size: 1.5em;
        color: #333;
        margin: 10px 0;
    }

    .product button {
        background-color: #28a745;
        color: white;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 1em;
        border-radius: 4px;
        transition: background-color 0.3s ease;
    }

    .product button:hover {
        background-color: #218838;
    }

    .product:hover {
        transform: scale(1.05);
    }

    /* Responsive Design */
    @media (max-width: 768px) {
        .product {
            width: 45%;
        }
    }

    @media (max-width: 480px) {
        .product {
            width: 100%;
        }
    }
</style>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<main class="mt-1 border rounded shadow p-4">
  <form role="form" method="post">
    {{ form.csrf_token }}
    <h1 class="h3 mb-3 fw-normal text-center">Please sign in</h1>

    <div class="form-floating">
      {{ form.name(placeholder="nombre", class="form-control mb-2", size="40") }}
      {{ form.name.label }}
        {% if form.name.errors %}
          {% for error in form.name.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
          {% endfor %}
        {% endif %}
    </div>
    <div class="form-floating">
      {{ form.password(placeholder="password", class="form-control mb-2") }}
      {{ form.password.label }}
        {% if form.password.errors %}
          {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}
        {% endif %}
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
  </form>
  <div class="mt-3 text-end">
    <a href="{{ url_for('google.login') }}">Login with Google</a>
  </div>
</main>

{% endblock %}

app/templates/tusCompras.html
{% extends "base.html" %}

{% block content %}


{% if carritosProductos %}
<div class="d-flex flex-wrap ">
{%for carrito in carritosProductos%}
<div class="border rounded p-2 shadow m-3">
    <h2 class="mt-3">Carrito {{loop.index}}</h2>
    <table class="table table-striped border">
        <!-- Total del carrito -->
        <h4 class="text-center">${{ carrito | map(attribute='total') | sum | price_format }} ARS</h4>
        <thead>
            <tr>
            <th scope="col">Producto</th>
            <th scope="col">Precio</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in carrito %}
            <tr>
                <td>{{ item.nombre }}</td>
                <td>${{ item.precio | price_format}}</td>
                <td>{{ item.cantidad }}</td>
                <td>${{ item.total | price_format }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
</div>

    
    
{% endfor %} 
</div>   
{% endif %}
 
{% endblock %}

{% block js %}
<script>
    
</script>
{% endblock %}

{% block css %}
<style>
</style>
{% endblock %}